name: Lint and Test

on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }} py ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "macos-latest"]
            python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.8-0' # from https://github.com/mamba-org/micromamba-releases
          environment-file: environment.yml
          cache-environment: true
          post-cleanup: 'none'
          create-args: >-
            python=${{ matrix.python-version }}
            black=24.10.0
            mypy=1.11.2
            isort=5.13.2 
            ruff=0.6.9
      - name: black
        shell: bash -l {0}
        run: "python -m black --check ."
      - name: isort
        shell: bash -l {0}
        run: "python -m isort -c -v ."
      - name: ruff
        shell: bash -l {0}
        run: "python -m ruff check"
      - name: test
        shell: bash -l {0}
        run: "python -m unittest discover"

